[versions]
assertj = "3.27.7"
flexmark = "0.64.8"
git-versioning = "6.4.4"
jacksonYaml = "2.19.0"
junit5 = "6.1.3"
kotlin = "2.4.10"
kover = "0.9.9"
ktlint-gradle = "14.2.0"

[libraries]
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
flexmark-all = { module = "com.vladsch.flexmark:flexmark-all", version.ref = "flexmark" }
jackson-dataformat-yaml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml", version.ref = "jacksonYaml" }
jackson-module-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jacksonYaml" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit5" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }

[plugins]
git-versioning = { id = "me.qoomon.git-versioning", version.ref = "git-versioning" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint-gradle" }
